#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias l='ls -l'
alias la='ls -la'
alias lsd="ls -l | grep --color=never '^d'"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias q="exit"
alias rm="rm -rf --"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Vim `v` with no arguments opens the current directory in Vim, otherwise opens the given location

v() {
    if [ $# -eq 0 ]; then
        vim .;
    else
        vim "$@";
    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases

. "$(get_os)/bash_aliases"
