#!/bin/bash

# ------------------------------------------------------------------------------
# | Navigation                                                                 |
# ------------------------------------------------------------------------------

alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# ------------------------------------------------------------------------------

# Folders

alias d="cd ~/Dropbox"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias p="cd ~/Projects"
alias ws="cd ~/Workspace"

# ------------------------------------------------------------------------------
# | Network                                                                    |
# ------------------------------------------------------------------------------

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# ------------------------------------------------------------------------------

if [ "$OS" == "osx" ]; then
    alias localip="ipconfig getifaddr en1"
fi

# ------------------------------------------------------------------------------
# | Package Managers                                                           |
# ------------------------------------------------------------------------------

# npm
# https://docs.npmjs.com/

if [ -x "$(command -v npm)" ]; then
    alias npmi="npm install"
    alias npmr="npm uninstall"
    alias npms="npm search"
    alias npmu="npm update"
fi

# ------------------------------------------------------------------------------

# OS specific package managers

# Homebrew
# http://brew.sh/

if [ -x "$(command -v brew)" ]; then
    alias brewd="brew doctor"
    alias brewi="brew install"
    alias brewr="brew uninstall"
    alias brews="brew search"
    alias brewu="brew update &&  \
                 brew upgrade --all && \
                 brew cleanup"
fi

# ------------------------------------------------------------------------------

# Update

if [ "$OS" == "osx" ]; then
    alias update="sudo softwareupdate --install --all && \
                  brewu && \
                  npmi -g npm && \
                  npmu -g"
fi

# ------------------------------------------------------------------------------
# | Shorter Commands                                                           |
# ------------------------------------------------------------------------------

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias g="git"
alias map="xargs -n1"
alias q="exit"
alias rm="rm -rf"

# ------------------------------------------------------------------------------

# List files

# List all files in long format
alias l="ls -lF"

# List all files in long format, including dot files
alias la="ls -laF"

# List only directories
alias lsd="ls -lF | grep --color=never '^d'"

# ------------------------------------------------------------------------------

# Copy to clipboard

alias cc="pbcopy"

# ------------------------------------------------------------------------------

# Copy my public key to the pasteboard

alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# ------------------------------------------------------------------------------

# Edit hosts file

alias hosts='sudo $EDITOR /etc/hosts'

# ------------------------------------------------------------------------------

# Empty Trash

if [ "$OS" == "osx" ]; then

    # Empty the trash, the main HDD and on all mounted volumes
    # and clear Apple’s system logs to improve shell startup speed

    alias emptytrash="sudo rm -frv /Volumes/*/.Trashes && \
                      sudo rm -frv ~/.Trash &&
                      sudo rm -frv /private/var/log/asl/*.asl"
fi

# ------------------------------------------------------------------------------

# Hide/Show files

# Hide/Show desktop icons
alias hide-desktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias show-desktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Hide/Show hidden files in Finder
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"

# ------------------------------------------------------------------------------

# Lock screen

if [ "$OS" == "osx" ]; then
    alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
fi

# ------------------------------------------------------------------------------

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`

alias mergepdf="/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py"
