#!/bin/bash

# -----------------------------------------------------------------------

enable_color_support() {

	if infocmp xterm-256color &> /dev/null; then
		export TERM="xterm-256color"
	fi

}

# -----------------------------------------------------------------------

# What kind of session we use ? Local, Telnet, SSH

set_connection() {
	if [[ -n "$SSH_CLIENT$SSH2_CLIENT" ]] ; then
		SESSION="\u@\h (ssh) "
	else
		local SESSION_SRC=$(who am i | sed -n 's/.*(\(.*\))/\1/p')
		if [[ -z "$SESSION_SRC" || "$SESSION_SRC" = ":"* ]] ; then
			SESSION=""
		else
			SESSION="\u@\h "
		fi
	fi
}

# -----------------------------------------------------------------------

set_prompt() {

	export GIT_PS1_SHOWDIRTYSTATE=true
	export GIT_PS1_SHOWUNTRACKEDFILES=true
	export GIT_PS1_SHOWCOLORHINTS=true

	set_connection

	# Pretty Prompt
	#
	# Terminal title (Unicorn)
	# [Cyan] Working directory [/Cyan]
	# [Light Purple] Git Prompt
	# [No Colour]:
	PS1='🦄 \[\e[0;36m\]${SESSION}\[\e[0;36m\]\W\[\033[0;35m\]$(__git_ps1 " (%s)")\[\e[0m\] ➜ '

	export PS1

}

# -----------------------------------------------------------------------

main() {
	enable_color_support
	set_prompt
}

main

# -----------------------------------------------------------------------

# Cleanup.

unset -f enable_color_support
unset -f main
unset -f set_prompt
