#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# ------------------------------------------------------------------------------

declare -r BASH_COMPLETION_PATH="$(brew --prefix 2> /dev/null)/share/bash-completion/bash_completion"

if [ -f "$BASH_COMPLETION_PATH" ]; then

	# Use the latest `bash-completion`.

	. "$BASH_COMPLETION_PATH"

	# Make Bash complete the `g` alias just like it does `git`.

	complete -o default -o nospace -F _git g

fi

# ------------------------------------------------------------------------------

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards

[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;
