#!/bin/bash

# ------------------------------------------------------------------------------
# | Navigation                                                                 |
# ------------------------------------------------------------------------------

alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# Folders

alias d="cd ~/Dropbox"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias p="cd ~/Projects"

# ------------------------------------------------------------------------------
# | Network                                                                    |
# ------------------------------------------------------------------------------

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# ------------------------------------------------------------------------------

if [ "$OS" == "osx" ]; then
    alias localip="ipconfig getifaddr en1"
fi

# ------------------------------------------------------------------------------
# | Package Managers                                                           |
# ------------------------------------------------------------------------------

# npm
# https://docs.npmjs.com/

if [ -x "$(command -v npm)" ]; then
    alias npmi="npm install"
    alias npmr="npm uninstall"
    alias npms="npm search"
    alias npmu="npm update"
fi

# ------------------------------------------------------------------------------

# OS specific package managers

# Homebrew
# http://brew.sh/

if [ -x "$(command -v brew)" ]; then
    alias brewd="brew doctor"
    alias brewi="brew install"
    alias brewr="brew uninstall"
    alias brews="brew search"
    alias brewu="brew update &&  \
                 brew upgrade && \
                 brew cleanup"
fi

# ------------------------------------------------------------------------------

# Update

if [ "$OS" == "osx" ]; then
    alias update="sudo softwareupdate --install --all && \
                  brewu && \
                  npmi -g npm && \
                  npmu -g"
fi

# ------------------------------------------------------------------------------
# | Shorter Commands                                                           |
# ------------------------------------------------------------------------------

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias g="git"
alias q="exit"
alias rm="rm -rf"

# ------------------------------------------------------------------------------

# List files

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
    colorflag="--color"
else # OS X `ls`
    colorflag="-G"
fi

# List all files colorized in long format
alias l="ls -lF ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -laF ${colorflag}"

# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls ${colorflag}"
export LS_COLORS="no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:"

# ------------------------------------------------------------------------------

# Copy to clipboard

alias cc="pbcopy"

# ------------------------------------------------------------------------------

# Empty Trash

if [ "$OS" == "osx" ]; then

    # Empty the trash, the main HDD and on all mounted volumes
    # and clear Apple’s system logs to improve shell startup speed

    alias emptytrash="sudo rm -frv /Volumes/*/.Trashes && \
                      sudo rm -frv ~/.Trash &&
                      sudo rm -frv /private/var/log/asl/*.asl"
fi

# ------------------------------------------------------------------------------

# Hide/Show files

# Hide/Show desktop icons
alias hide-desktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias show-desktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Hide/Show hidden files in Finder
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"

# ------------------------------------------------------------------------------

# Lock screen

if [ "$OS" == "osx" ]; then
    alias lock="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
fi

# ------------------------------------------------------------------------------

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`

alias mergepdf="/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py"
