#!/bin/bash

# Shell Variables
# http://linux.die.net/man/1/bash

# ------------------------------------------------------------------------------

# Make vim the default editor
export EDITOR='vim'

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines contained in the
# history file (default value is 500)
export HISTFILESIZE=10000

# Don't add certain commands to the history file
export HISTIGNORE='g:c:cd:cd -:clear:history:exit:q:l:la:lsd:pwd:* --help'

# Increase the maximum number of commands recorded in the
# command history (default value is 500)
export HISTSIZE=10000

# Prefer GB English and use UTF-8 encoding
export LANG='en_GB'
export LC_ALL='en_GB.UTF-8'

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page
export MANPAGER='less -X';

# Always enable colored `grep` output
export GREP_OPTIONS='--color=auto';

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
