#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

	declare -r CURRENT_DIRECTORY="$(pwd)"

	declare -r -a FILES_TO_SOURCE=(
		"bash_autocomplete"
		"bash_options"
		"bash_prompt"
		"shell_aliases"
		"shell_exports"
		"shell_functions"
		"bash.local" # Local settings not be under version control.
	)

	local file=""
	local i=""

	cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" \
		&& . "../macos/utils.sh"

	# shellcheck disable=SC2034
	declare -r OS="$(get_os)"

	for i in ${!FILES_TO_SOURCE[*]}; do

		file="$HOME/.${FILES_TO_SOURCE[$i]}"

		[ -r "$file" ] \
			&& . "$file"

	done

	cd "$CURRENT_DIRECTORY"

}

source_bash_bin_dir() {

	# Adding dotfiles `bin` to `$PATH`
	export PATH="$PATH:$HOME/projects/dotfiles/bin";

}

# -----------------------------------------------------------------------

source_bash_files
source_bash_bin_dir
unset -f source_bash_files

# -----------------------------------------------------------------------

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).

clear
