#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

enable_color_support() {

	if infocmp xterm-256color &> /dev/null; then
		export TERM="xterm-256color"
	fi

}

# -----------------------------------------------------------------------

set_prompts() {

	export GIT_PS1_SHOWDIRTYSTATE=true
	export GIT_PS1_SHOWUNTRACKEDFILES=true
	export GIT_PS1_SHOWCOLORHINTS=true

	# pretty prompt
	# I use base-16 'ocean' for my terminal colours http://chriskempson.github.io/base16/#ocean
	# if you use iTerm grab the colours file here https://github.com/christianbundy/spacegrey-iterm
	export PS1='🦄 🔹\[\e[0;36m\]\[\e[0;36m\] \W\[\033[0;35m\]$(__git_ps1 " (%s)")\[\e[0m\]: '

}

# -----------------------------------------------------------------------

main() {
	enable_color_support

	set_prompts
}

main

# -----------------------------------------------------------------------

# Cleanup.

unset -f enable_color_support
unset -f main
unset -f set_prompts
