#!/bin/zsh

# -----------------------------------------------------------------------

source_shell_files() {

	[[ -f ~/.shell_aliases ]] && source ~/.shell_aliases
	[[ -f ~/.shell_exports ]] && source ~/.shell_exports
	[[ -f ~/.shell_functions ]] && source ~/.shell_functions

	# Load extra (docker alias)
	[[ -f ~/.docker_aliases ]] && source ~/.docker_aliases

	# Load extra (local/private) settings
	[ -f ~/.zsh.local ] && source ~/.zsh.local

}

source_shell_bin() {

	# Adding dotfiles `bin` to `$PATH`
	export PATH="$PATH:$HOME/projects/dotfiles/bin";

}

# -----------------------------------------------------------------------

source_shell_files
source_shell_bin
unset -f source_shell_files

# -----------------------------------------------------------------------

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).

clear
