#!/bin/zsh

# -----------------------------------------------------------------------

# Path to your oh-my-zsh installation.
export ZSH=/Users/adsric/.oh-my-zsh

# Set name of the theme to null to load
# prompt `pure` (See https://github.com/sindresorhus/pure)
ZSH_THEME=""

# Set ZSH custom directory for prompt and theme.
ZSH_CUSTOM="$HOME/projects/dotfiles/zsh"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras)

source $ZSH/oh-my-zsh.sh