#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash
brew install bash-completion
# Add the new shell to the list of legit shells
sudo bash -c "echo /usr/local/bin/bash >> /private/etc/shells"
# Change the shell for the user
chsh -s /usr/local/bin/bash

# Install node
brew install node

# Install more recent versions of some OS X tools
brew install vim --override-system-vi
brew tap homebrew/dupes
brew install homebrew/dupes/grep

# Install OS X applications and large binaries like a tool
brew install caskroom/cask/brew-cask

# Install everything else
brew install ack
brew install git
brew install ffmpeg
brew install imagemagick --with-webp
brew install jpeg
brew install ngrep
brew install rename
brew install optipng
brew install tree
brew install wget

# Remove outdated versions from the cellar
brew cleanup
